# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('branch', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Other'), (b'?', b'Unknown')], default=b'?', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('race', models.CharField(choices=[(b'ASIAN', b'Asian'), (b'BLACK', b'Black'), (b'LATINO', b'Latino'), (b'WHITE', b'White'), (b'OTHER', b'Other'), (b'?', b'Unknown')], default=b'?', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
