# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160921_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataSource', models.CharField(max_length=500)),
                ('has_errors', models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], default=b'?', max_length=1)),
                ('exec_start', models.CharField(max_length=500)),
                ('erros_prep', models.CharField(max_length=5000)),
                ('erros_executing', models.CharField(max_length=5000)),
                ('erros_saving', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='invite',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'GAY'), (b'?', b'Unknown')], default=b'?', max_length=1),
        ),
    ]
