# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160921_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Other'), (b'?', b'Unknown')], default=b'?', max_length=1),
        ),
    ]
