# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160921_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='amos',
            name='exec_end',
            field=models.CharField(default=b'SOME STRING', max_length=500),
        ),
        migrations.AlterField(
            model_name='amos',
            name='has_errors',
            field=models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No'), (b'DN', b'Dont know')], default=b'?', max_length=1),
        ),
    ]
