# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160921_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amos',
            name='dataSource',
            field=models.CharField(default=b'Nome da fonte de dados', max_length=500),
        ),
        migrations.AlterField(
            model_name='amos',
            name='erros_executing',
            field=models.CharField(default=b' ', max_length=5000),
        ),
        migrations.AlterField(
            model_name='amos',
            name='erros_prep',
            field=models.CharField(default=b' ', max_length=5000),
        ),
        migrations.AlterField(
            model_name='amos',
            name='erros_saving',
            field=models.CharField(default=b' ', max_length=5000),
        ),
        migrations.AlterField(
            model_name='amos',
            name='exec_end',
            field=models.CharField(default=b'dd/mm/aaaa hh:mm', max_length=500),
        ),
        migrations.AlterField(
            model_name='amos',
            name='exec_start',
            field=models.CharField(default=b'dd/mm/aaaa hh:mm', max_length=500),
        ),
        migrations.AlterField(
            model_name='amos',
            name='has_errors',
            field=models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No'), (b'DN', b'Dont know')], default=b'DN', max_length=1),
        ),
    ]
