# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160921_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amos',
            name='exec_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='amos',
            name='exec_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='amos',
            name='has_errors',
            field=models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No'), (b'DN', b'Dont know')], default=b'DN', max_length=2),
        ),
    ]
