# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160922_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amos',
            name='exec_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
