# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160922_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='amos',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
